name: Glovensys
favicon: null
layout_spectrum: 0.8074949521105736
typography_spectrum: 0.015020915074273944
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#140603'
    - '#795a77'
    - '#5c4460'
    - '#ffffff'
    - '#fd8467'
  brandStrength: 0.9362696530297399
  lightness: 0.8447283885907382
  saturation: 0.6774972674902529
  rhythmicContrast: 0.3813308996614069
purpose: []
